name: test-scala
run-name: ${{ github.actor }} is running the scala test  
on: [push]
jobs:
  test_scala_2-3-1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: typelevel/download-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1
      - name: compile scala 2.3.1    
        run: scala-cli --scala 3.2.1 scala/RDF.scala 
 test_scala_nighly:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: typelevel/download-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1
      - name: compile scala nightly
        run: scala-cli --scala 3.nightly scala/RDF.scala
